# Generated by Django 3.1.6 on 2021-02-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('current_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('goal', models.CharField(choices=[('LW', 'Lose Weight'), ('MW', 'Maintain Weight'), ('GW', 'Gain Weight'), ('GM', 'Gain Muscle')], max_length=2)),
            ],
        ),
    ]
